Testing params:
  stage: test
  script:
    - echo "Hello World" | tee -a artifact_text.txt
    - echo "Current date is" | tee -a artifact_text.txt
    - date | tee -a artifact_text.txt
    - echo "Commit-SHA, Commit-branch, merge-request-id"  | tee -a artifact_text.txt
    - echo "$CI_COMMIT_SHA" | tee -a artifact_text.txt
    - echo "$CI_COMMIT_BRANCH" | tee -a artifact_text.txt
    - echo "$CI_MERGE_REQUEST_IID" | tee -a artifact_text.txt
  artifacts:
    expire_in: "1 day"
    name: "gitlab-ci-artifact"
    paths:
      - artifact_text.txt